SET NAMES UTF8;
DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog CHARSET=UTF8;
USE blog;

CREATE TABLE user(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32),
  password VARCHAR(64),
  avatar VARCHAR(32),
  gender VARCHAR(32),
  bio VARCHAR(250)
);

CREATE TABLE article(
  article_id INT PRIMARY KEY AUTO_INCREMENT,
  author_id INT,
  author VARCHAR(32),
  title VARCHAR(32),
  content VARCHAR(255),
  pv BIGINT
);

